[package]
name = "swiss_army_bot"
version = "1.4.0-nein"
authors = ["Steven vanZyl <rushsteve1@rushsteve1.us>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# TODO optimize feature flags

[dependencies]
askama_gotham = "^0.13"
chrono = "^0.4"
clokwerk = "^0.4"
env_logger = "^0.10"
gotham = "^0.7"
gotham_derive = "^0.7"
lazy_static = "^1.4"
log = "^0.4"
once_cell = "*"
regex = "*"
scraper = "^0.14"
serde = "*"
serde_derive = "*"

[dependencies.askama]
version = "^0.11"
default_features = false
features = [ "with-gotham" ]

[dependencies.serenity]
version = "^0.11"
default_features = false
features = [ "client", "gateway", "rustls_backend", "model" ]

[dependencies.sqlx]
version = "^0.6"
features = [ "chrono", "sqlite", "runtime-tokio-rustls" ]

[dependencies.tokio]
version = "^1.25"
features = [ "full" ]

[dependencies.reqwest]
version = "*"
default_features = false
features = [ "rustls-tls", "gzip" ]
