[package]
name = "swiss_army_bot"
version = "1.7.3-nein"
authors = ["Steven vanZyl <rushsteve1@rushsteve1.us>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0"
askama_axum = "*"
axum = "^0.7"
chrono = "*"
chrono-tz = "*"
clokwerk = "^0.4"
opentelemetry = "*"
opentelemetry-otlp = { version = "^0.14", features = ["tls", "tls-roots"] }
opentelemetry_sdk = { version = "*", features = ["rt-tokio"] }
regex = "*"
scraper = "^0.18"
serde = "*"
serde_derive = "*"
tonic = "^0.9"
tracing = "*"
tracing-opentelemetry = "^0.22"
tracing-subscriber = "*"

[dependencies.askama]
version = "^0.12"
default_features = false
features = [ "with-axum" ]

[dependencies.reqwest]
version = "*"
default_features = false
features = [ "rustls-tls", "gzip" ]

[dependencies.serenity]
version = "^0.12"
default_features = false
features = [ "client", "gateway", "rustls_backend", "model" ]

[dependencies.sqlx]
version = "^0.7"
default_features = false
features = [ "macros", "migrate", "chrono", "sqlite", "runtime-tokio" ]

[dependencies.tokio]
version = "^1.35"
features = [ "full" ]
