CREATE TABLE IF NOT EXISTS drunk (
    id INTEGER PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL UNIQUE,
    user_name TEXT NOT NULL,
    beer INTEGER NOT NULL DEFAULT 0,
    wine INTEGER NOT NULL DEFAULT 0,
    shots INTEGER NOT NULL DEFAULT 0,
    cocktails INTEGER NOT NULL DEFAULT 0,
    derby INTEGER NOT NULL DEFAULT 0,
    water INTEGER NOT NULL DEFAULT 0,
    last_drink TEXT,
    last_spill DATETIME,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
